SYSLOG_HOST = '0.0.0.0'
SYSLOG_PORT = 1540
LOKI_URL = 'https://logs.domain.com/api/prom/push'
GEOIP_DB_PATH = "/geo/db/GeoLite2-City.mmdb"
ENABLE_GEOIP = False
THREAD_MULTIPLIER = 2  # Multiplikator of the Worker-Threads
QUEUE_SIZE = 10000  # Queue Size
QUEUE_THREAD_MULTIPLIER = 4
JOB_LABEL="opnsense-parser-test"
LOG_BATCH_SIZE=100
#LOKI_AUTH_USERNAME=
#LOKI_AUTH_PASSWORD=
#LOKI_AUTH_VERIFY_SSL=